name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  |
        docker build . --file Dockerfile.dev --tag marcusbalbi/docker-ci-example-frontend:latest
        docker run -e CI=true marcusbalbi/docker-ci-example-frontend:latest npm run test
